name: Semantic Version

on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Get required packages
        run: |
          go get -u github.com/go-git/go-git/v5
          go get -u github.com/Masterminds/semver

      - name: Get semantic version
        run: go run release.go
