name: Semantic Version
on:
  push:
    branches:
      - main

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Git
        run: sudo apt-get update && sudo apt-get install git -y

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Get semantic version
        run: |
          go get github.com/go-git/go-git/v5
          go get github.com/go-git/go-git/v5/plumbing/object
          go get github.com/go-git/go-git/v5/plumbing/semver
          go run main.go
