name: Renovate
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Renovate
        run: npm install -g renovate
      - name: Run Renovate
        run: renovate --token ${{ secrets.RENOVATE_TOKEN }} --platform github --dep neeltom92/image-updater --autodiscover
